# Generated by Django 4.2.11 on 2024-03-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_telegramauthorization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramauthorization",
            name="authorization_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
