# Generated by Django 4.2.11 on 2024-04-01 08:53

from django.db import migrations, models
import validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramauthorization",
            name="telegram_id",
            field=models.PositiveIntegerField(
                unique=True, validators=[validators.validate_telegram_id]
            ),
        ),
    ]
