# Generated by Django 4.2.11 on 2024-03-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
