# Generated by Django 4.2.11 on 2024-03-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Забронировано"), (1, "Отменен"), (2, "Истек")], default=0
            ),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
